# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ed Freyfogle
email: freyfogle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ed Freyfogle's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://freyfogle.com" # the base hostname & protocol for your site
twitter_username: freyfogle
github_username:  freyfogle
encoding: utf-8
timezone: Europe/Madrid

# Build settings
markdown: kramdown
